podTemplate(containers: [
  containerTemplate(
    name: 'gradle',
    image: 'gradle:6.3-jdk14',
    command: 'sleep',
    args: '30d'
    ),
  ]) {
    node(POD_LABEL) {
      stage('Run pipeline against a gradle project - test MAIN') {
        container('gradle') {
          stage('Build a gradle project') {
            echo "I am the ${env.BRANCH_NAME} branch"
            git branch: 'feature', credentialsId: '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', url: 'https://github.com/slykmh/week6.git'
            sh '''
            cd sample1
            chmod +x gradlew
            ./gradlew test
            '''
          }
          stage('Code coverage') {
            sh 'printenv'
            echo "My CC branch is: ${env.CHANGE_BRANCH}"
            if (env.BRANCH_NAME == "feature") {
              echo "I am the ${env.BRANCH_NAME} branch"
            }
            if (env.BRANCH_NAME == "feature") {
              echo "I am the ${env.BRANCH_NAME} branch"
              try {
                        sh '''
		        pwd
			cd /var/jenkins_home/workspace/wee6-multibranch_feature/
                        ./gradlew jacocoTestCoverageVerification
                        ./gradlew jacocoTestReport
                                                '''
                    } catch (Exception E) {
                        echo 'Failure detected'
                    }
              publishHTML (target: [
                        reportDir: 'Chapter08/sample1/build/reports/tests/test',
                        reportFiles: 'index.html',
                        reportName: "JaCoCo Report"
              ])
		
            }
          }
        }
      }
    }
}
